config/routes.rb
Rails.application.routes.draw do

  resources :flats

  root 'flats#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new

  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/destroy.html.erb
<h1>Flats#destroy</h1>
<p>Find me in app/views/flats/destroy.html.erb</p>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<div class="container">
  <h1>List of flats</h1>
  <div class="row">
    <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" >
          <div class="card-description">
            <h1><%= flat.address %></h1>
            <h2><%= flat.description %></h2>
          </div>
          <div class="card-category">
            <i class="fas fa-pound-sign"><%= flat.price_per_night %></i>
            <i class="fas fa-users"><%= flat.number_of_guests %></i>
          </div>
          <div class="green">
            <%= link_to 'More-info', flat_path(flat.id) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<!-- style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('https://kitt.lewagon.com/placeholder/cities/shanghai');" -->

app/views/flats/new.html.erb
<h1>Flats#new</h1>
<p>Find me in app/views/flats/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>